import type { Metadata } from "next";
import { Inter, Onest, Oxanium, Geist } from "next/font/google";
import "./globals.css";
import TopBar from "@/components/shared/TopBar";
import localFont from "next/font/local";
import FooterSection from "@/components/shared/FooterSection";
import { ThemeProvider } from "@/components/theme-provider"
import { UmamiAnalytics } from "@/components/umami-analitics";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter"
})

const onest = Onest({
  variable: "--font-onest",
  subsets: ["latin"]
})

const oxanium = Oxanium({
  variable: "--font-oxanium",
  subsets: ["latin"]
});


const geist = Geist({
  variable: "--font-geist",
  subsets: ["latin"],
});

const menlo = localFont({
  src: [
    {
      path: "../public/fonts/Menlo-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-menlo",
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.variable} ${onest.variable} ${oxanium.variable} ${menlo.variable} ${geist.variable} antialiased bg-background dark:bg-background`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <TopBar />
          {children}
          <FooterSection />
        </ThemeProvider>
        <UmamiAnalytics />
      </body>
    </html>
  );
}
